version: "3.8"

services:
  fiber-app:
    build: .

  nginx:
    image: nginx:alpine
    depends_on:
      - fiber-app
    ports:
      - "80:80"
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf:ro
    command: ["/bin/sh", "-c", "mkdir -p /data/nginx/cache && exec nginx -g 'daemon off;'"]
